// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6e4EWOcX69KnClq7xBpiErqbi7brytBg',
    appId: '1:988731635472:web:cb0b7836d3c32ac1805795',
    messagingSenderId: '988731635472',
    projectId: 'make-mode-tracker-giseon',
    authDomain: 'make-mode-tracker-giseon.firebaseapp.com',
    storageBucket: 'make-mode-tracker-giseon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNayo9qhmzByJT6H0KMu1Nln3Ph8O02HU',
    appId: '1:988731635472:android:e89dc6325194de1c805795',
    messagingSenderId: '988731635472',
    projectId: 'make-mode-tracker-giseon',
    storageBucket: 'make-mode-tracker-giseon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuy-3FZAILsfy1NtaGR9ytDpmP5zLgWc0',
    appId: '1:988731635472:ios:874c77ec01edd5be805795',
    messagingSenderId: '988731635472',
    projectId: 'make-mode-tracker-giseon',
    storageBucket: 'make-mode-tracker-giseon.appspot.com',
    iosBundleId: 'com.example.finalmood',
  );
}
